# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:  |
          aws cloudformation deploy \
          --stack-name ansibleExercise \
          --template-file template.yml
  ssh_ansible:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["58:61:bc:84:e9:90:c3:7c:75:3d:c3:c4:0b:1e:96:f7"]
      - run:
          name: install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory main.yml
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: smoke test
          command: |
            if curl -s --head "https://google.com"
            then
              echo "It worked!"
            else
              echo "It failed"
            fi
      


# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      # - create_infrastructure
      # - ssh_ansible
      - smoke_test
